# This workflow will install will install app dependencies and run unit test
# Then test coverage has a benchmark of 98% 
# notify on slack

name: dockerize app

on:
  push:
    branches: ["master"]
  # pull_request:
  #
jobs:
  Push-to-docker: 
    needs: unit-test     
    runs-on: ubuntu-latest
    steps:
      - name: Setup repo
        uses: actions/checkout@v3

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}   
         
      - name: Build image and push to Docker Hub Container Registry
        uses: docker/build-push-action@v2
        with:
          # relative path to the place where source code with Dockerfile is located
          context: app/
          # Note: tags has to be all lower-case
          tags: |
           emmanuelekama/node-web-app:0.0.01
          
          push: true 
