

# This workflow will install will install app dependencies and run unit test
# Then test coverage has a benchmark of 98% 
# notify on slack

name: unit test and coverage

on:
  push:
    branches: ["test/workflow"]
  # pull_request:
  #   branches: ["master"]

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: Setup repo
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}   
      - run: |
         pwd 
         ls -al
         cd app
         npm install 
         npm run build 
         npm run test:coverage
         unit-test:

  Push-to-docker: 
    needs: unit-test     
    runs-on: ubuntu-latest
    steps:
      - name: Setup repo
        uses: actions/checkout@v3

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}   
         
      - name: Build image and push to Docker Hub Container Registry
        uses: docker/build-push-action@v2
        with:
          # relative path to the place where source code with Dockerfile is located
          context: app/
          # Note: tags has to be all lower-case
          tags: |
           emmanuelekama/node-web-app:0.0.01
          
          push: true 

  make_to_main:
    needs: unit-test     
    runs-on: ubuntu-latest
    steps:
      - name: Setup repo
        uses: actions/checkout@v3

      - name: Login to DockerHub
        uses: docker/login-action@v2  

      -  name: Build image and push to Docker Hub Container Registry
         uses: docker/build-push-action@v2
         with:
          push: ${{ github.ref == 'refs/heads/circleci-project-setup' }}
          # relative path to the place where source code with Dockerfile is located
          # context: app/
          # # Note: tags has to be all lower-case
          # tags: |
          #  emmanuelekama/node-web-app:0.0.01
              

                  

       