

# This workflow will install will install app dependencies and run unit test
# Then test coverage has a benchmark of 98% 
# notify on slack

name: unit test and coverage

on:
  push:
    branches: ["test/workflow"]
  # pull_request:
  #   branches: ["master"]

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: Setup repo
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}   
      - run: |
         pwd 
         ls -al
         cd app
         npm install 
         npm run build 
         npm run test:coverage

 
  merge_to_master:
    needs: unit-test     
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          ref: ${{ github.head_ref }}
      - name: Create report file
        run: date +%s > report.txt
      - name: Commit report
        uses: peter-evans/create-pull-request@v4
                # uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.PAT }}
          committer: 'ekama'
          base: ${{ github.head_ref }}
          author: uloho 
          branch: master
          body: |
            'test body pr'
        # run: |
        #   git config --global user.name ekamanelly
        #   git config --global user.email ekamanelly@users.noreply.github.com
        #   git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
        #   git push origin master

      # -  name: Build image and push to Docker Hub Container Registry
      #    uses: docker/build-push-action@v2
      #    with:
      #     push: ${{ github.ref == 'refs/heads/circleci-project-setup' }}
      #     # relative path to the place where source code with Dockerfile is located
      #     # context: app/
      #     # # Note: tags has to be all lower-case
      #     # tags: |
      #     #  emmanuelekama/node-web-app:0.0.01
              

                  

       